spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 987586143497-fllhhc15ep1sd49osbnpno7ntlumk045.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile