spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 511016516698-hr7unst1j7msevdmb0tmicdnr332ns90.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile